from alembic import op
import sqlalchemy as sa
"""add youtube tables
"""
revision = '8f715e99d281'
down_revision = '0001_initial'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_credentials_id'), 'youtube_credentials', ['id'], unique=False)
    op.create_table('youtube_playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_playlists_id'), 'youtube_playlists', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_playlists_id'), table_name='youtube_playlists')
    op.drop_table('youtube_playlists')
    op.drop_index(op.f('ix_youtube_credentials_id'), table_name='youtube_credentials')
    op.drop_table('youtube_credentials')
    # ### end Alembic commands ###
